ORM 2 objectives
LaunchCodeEducation/lc101-learning-objectives pull request #20
Opened 2020-01-09 14:47 UTC by chrisbay

2020-01-10 22:04 UTC, chrisbay commented
![](https://github.trello.services/images/mini-trello-icon.png) [EPIC - Java Lesson 17 🎆](https://trello.com/c/TQv0SGto/370-epic-java-lesson-17-%F0%9F%8E%86)

2020-01-16 16:34 UTC, jimflores5 requested changes

2020-01-16 16:34 UTC, jimflores5 commented on unit2-java/lesson16.rst
>  - Describe what a data layer is and how it is used in ORM
Comma addition: "...layer is, and how..."

2020-01-16 16:34 UTC, jimflores5 commented on unit2-java/lesson16.rst
>  - Explain what object-relational mapping refers to
I'm not sure of the grammar acceptability of ending a sentence with "to".  Perhaps, "...mapping means"?

2020-01-16 16:34 UTC, jimflores5 commented on unit2-java/lesson16.rst
>  - Use the following annotations and describe what they accomplish:
This sentence is rendered as bold and italic. I think you need to add an empty line between it and the sub-list.

2020-01-16 16:34 UTC, jimflores5 commented on unit2-java/lesson17.rst
> +- Describe the one-to-many relationship
This was done in the SQL lessons.

2020-01-16 16:34 UTC, jimflores5 commented on unit2-java/lesson17.rst
> +One-to-many Relationships
Title Case?  "One-to-Many Relationships"

2020-01-16 16:34 UTC, jimflores5 commented on unit2-java/lesson17.rst
> +- Use the following annotations and describe what they accomplish:
This line is rendered bold and italic.  Add an empty line between it and the sub-list.

2020-01-16 16:34 UTC, jimflores5 commented on unit2-java/lesson17.rst
> +Many-to-many Relationships
"Many-to-Many"?

2020-01-16 17:00 UTC, merged