Drafts REST objectives
LaunchCodeEducation/lc101-learning-objectives pull request #21
Opened 2020-01-10 22:03 UTC by chrisbay

2020-01-10 22:04 UTC, chrisbay commented
![](https://github.trello.services/images/mini-trello-icon.png) [EPIC - Java Lesson 18 🎆](https://trello.com/c/GRByPWcF/372-epic-java-lesson-18-%F0%9F%8E%86)

2020-01-16 16:42 UTC, jimflores5 requested changes

2020-01-16 16:42 UTC, jimflores5 commented on unit2-java/lesson18.rst
> +- Understand the advantages using REST
"...advantages of using REST"

2020-01-16 16:42 UTC, jimflores5 commented on unit2-java/lesson18.rst
>  - Explain idempotence in REST
Is "idempotence" really a word?  If so, *italics* or **bold** to emphasize that it is NOT a weird typo.

2020-01-16 17:03 UTC, merged