Lesson 12 Learning Objectives
LaunchCodeEducation/lc101-learning-objectives pull request #38
Opened 2020-06-02 20:40 UTC by gildedgardenia

2020-06-05 13:49 UTC, chrisbay requested changes
Looks good, with one outstanding question regarding validation attributes.

2020-06-05 13:49 UTC, chrisbay commented on unit2-csharp/lesson12.rst
> +- Use the ``[Required]`` attribute
I'm wondering if there are other [built-in validation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#built-in-attributes) attributes that would be good to expose learners to. I'm not sure which ones would fit well within the coding events app, but `[Range]`, `[StringLength]`, and `[EmailAddress]` seem like good, commonly-used candidates.

2020-06-05 13:49 UTC, chrisbay commented on unit2-csharp/lesson12.rst
> +- Use the ``[Required]`` attribute
One thought is to see what we did for the corresponding Java lesson.

2020-06-05 18:49 UTC, chrisbay approved these changes

2020-06-10 17:48 UTC, gildedgardenia commented on unit2-csharp/lesson12.rst
> +- Use the ``[Required]`` attribute
Added!

2020-06-10 18:20 UTC, merged